# Generated by Django 2.0.5 on 2018-06-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0002_auto_20180614_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triko_model',
            name='image',
            field=models.ImageField(height_field=200, upload_to='media/image', width_field=100),
        ),
    ]
