# Generated by Django 2.0.5 on 2018-06-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0003_auto_20180614_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triko_model',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
