# Generated by Django 2.0.5 on 2018-06-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0004_auto_20180614_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='triko_model',
            name='description',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
