# Generated by Django 2.0.5 on 2018-06-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0006_employee_person_buy_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_buy_product',
            name='code',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
