# Generated by Django 2.0.5 on 2018-07-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0008_auto_20180619_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=11)),
                ('email_facebook', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('model_define', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Triko.Triko_Model')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='person_buy_product',
            name='employe',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='person_buy_product',
        ),
    ]
