# Generated by Django 2.0.5 on 2018-07-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0009_auto_20180702_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='model_define',
        ),
        migrations.AddField(
            model_name='trader',
            name='model_define',
            field=models.ManyToManyField(to='Triko.Triko_Model'),
        ),
    ]
