# Generated by Django 2.0.5 on 2018-07-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0010_auto_20180702_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='quentity',
            field=models.IntegerField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
