# Generated by Django 2.0.5 on 2018-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0011_trader_quentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='triko_model',
            name='price',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='trader',
            name='quentity',
            field=models.IntegerField(),
        ),
    ]
