# Generated by Django 2.0.5 on 2018-07-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0012_auto_20180703_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='model_define',
        ),
        migrations.AddField(
            model_name='trader',
            name='model_define',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Triko.Triko_Model'),
            preserve_default=False,
        ),
    ]
