# Generated by Django 2.0.5 on 2018-07-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0016_auto_20180727_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(default=1, upload_to='color/'),
            preserve_default=False,
        ),
    ]
