# Generated by Django 2.0.5 on 2018-07-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Triko', '0017_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='imag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='color',
            name='model',
        ),
        migrations.AddField(
            model_name='triko_model',
            name='colors',
            field=models.ManyToManyField(to='Triko.color'),
        ),
    ]
